### ISSUE TITLE
Only wrap the components that we can hot reload

### ISSUE THREAD

**Issue by MiguelMadero** [adopted-ember-addons/ember-cli-hot-loader#14]
"the components that we care about"
That list may initially be defined based on the application name, but eventually, we probably want to wrap addons where `isDeveloping` is true.

**Comment by toranb** [comment]
Ah great point - so does the isDeveloping flag only return true for the given app's components (no addons unless they are turned on explicitly) ? I didn't realize this was a public api

**Comment by MiguelMadero** [comment]
> Ah great point - so does the isDeveloping flag only return true for the given app's components (no addons unless they are turned on explicitly) ? I didn't realize this was a public api

I was thinking of doing a union of the current app's components (based on the namespace) and all the components defined in addons that have `isDeveloping: true`.
