### ISSUE TITLE
Feature: support for addons and engines

### ISSUE THREAD

**Issue by MiguelMadero** [adopted-ember-addons/ember-cli-hot-loader#20]
https://github.com/toranb/ember-cli-hot-loader/blob/moves-samples-to-dummy/addon/instance-initializers/hot-loader-livereload-plugin.js#58

**Comment by toranb** [comment]
@MiguelMadero that link above is 404 (my fault maybe?) -any idea if that PR you had up is good enough to track the discussion/ work?

I'm in need of something that will let us hot reload from the addon dummy app and the engine dummy app (along with normal app dev). What will it take to support these 3 use cases from your experience?

**Comment by MiguelMadero** [comment]
Looks like the link was pointing to a branch that was deleted. I just pushed the branch again so it works see https://github.com/toranb/ember-cli-hot-loader/blob/moves-samples-to-dummy/addon/instance-initializers/hot-loader-livereload-plugin.js#L58 

Hope that helps.

**Comment by MiguelMadero** [comment]
I think this https://github.com/toranb/ember-cli-hot-loader/pull/23 might be useful

**Comment by toranb** [comment]
I've renamed this issue to point out explicitly that this doesn't yet support addons or engines

**Comment by lukemelia** [comment]
We have a internal addon of shared components that this addon seems like it would be super helpful for. I've subscribed to this issue so I know when I can try it in that context.
